### ISSUE TITLE
cannot mark channel/feeds as read

### ISSUE THREAD

**Issue by githubuser232153354** [brief-rss/brief#507] opened 2020-11-06 15:51 UTC
This is an example of a rss channel i cannot mark as read.
With every update, feeds reappear.

xmlUrl="https://www.cyberdefence24.pl/feed/?category=69"/

**Comment by tanriol** [comment] 2024-05-02 23:33
Closing as the page no longer exists (error 404), so cannot reproduce the problem. Feel free to reopen if you have another feed exhibiting the same problem.

**Closed by tanriol** 2024-05-02 23:33 UTC
