### ISSUE TITLE
Lost all bookmarks item 

### ISSUE THREAD

**Issue by Patclash** [brief-rss/brief#340] opened 2018-01-26 10:24 UTC
Yesterday I lost all my bookmarked item :(

Is there a way to recover them or to import them from a other brief.sqlite file I have on an other machine running Brief 2.4.0 on Firefox 52.6 ? ....

**Comment by wisedevman** [comment] 2018-03-06 07:55
The same happened to me.

**Comment by corvus89** [comment] 2018-03-13 17:50
Same problem for me. Suddenly all channels disappeared :'( . It happened on Brief 2.55 FF 58.0.1. After bug occurred i tried updating to FF 59.0 I still get empty list.
Console output:
Brief: opening database in persistent storage database.js:43:9
Brief: 69 feeds in database database.js:176:9
Brief: opened database with 31387 entries database.js:53:9
SQLite file from storage/permanent still got 81MB

**Comment by corvus89** [comment] 2018-03-13 19:00
Be aware that I have no experience in writing extensions. I tried look through process with debuger. 
FeedList_getAllFeeds (feedlist.js#496)
FeedList_getAllFeeds (feedlist.js#495)
FeedList_rebuild (feedlist.js#651)
init (brief.js#89)

Returned list is empty. All f objects have field hidden set to 1

Could it that be a source of the problem?

**Comment by tanriol** [comment] 2018-03-24 22:19
@Patclash Seems like this bug is already found and is being fixed. Recovery should be possible as the bookmarks are probably still there.

@wisedevman Have you lost the bookmarked items or everything?

@corvus89 This looks like a separate problem - and "all feeds are hidden" is a symptom, not the root cause. It's possible to unhide them, but we still won't know why they became hidden.

**Comment by wisedevman** [comment] 2018-03-25 08:15
@tanriol Everything, all feeds listed on the right. I don't know how to recover them.
I backup brief db in firefox profile folder, but i don't know how to access them.

**Comment by tanriol** [comment] 2018-03-25 09:01
@wisedevman In my understanding "on the right" is the archive of entries, not the list of feeds themselves. Which one do you want to recover?

**Comment by wisedevman** [comment] 2018-03-26 16:02
@tanriol sorry, I meant left sidebar

**Comment by tanriol** [comment] 2018-06-05 00:03
Closing as this seems to be fixed. @wisedevman, if you're interested, recovering hidden feeds should be possible with Brief 2.5.7 and/or a [magic command](https://github.com/brief-rss/brief/issues/355#issuecomment-387483095).

**Closed by tanriol** 2018-06-05 00:03 UTC
Labels: P1, T-bug
