### ISSUE TITLE
Brief not working

### ISSUE THREAD

**Issue by bostongarden** [brief-rss/brief#526] opened 2023-05-29 10:17 UTC
I have used brief for years and for the past 2 days it will not load anything. Just a blank page. Suggestions? I have version 2.6.1
Thanks!

**Comment by tanriol** [comment] 2023-05-30 07:16
Hi, sorry for slow response.
By "blank page" do you mean the basic page (sidebar / buttons) is there, just no feeds?
Could you please check the developer console of the Brief tab (F12, "Console" tab) for error messages?

**Comment by bostongarden** [comment] 2023-05-30 09:15
The sidebar with 3 headers/llnks is there (refresh, organize, options) but
the body of the sidebar is blank, and the buttons don't do anything. The
main body is blank.
Thanks,
Dave

**Comment by bostongarden** [comment] 2023-05-30 09:23
I was able to get it to work again by exporting OPML from an old profile,
and importing the OPML in the new profile. Would still be interested to
know what happened and how to fix it if I did not have the old FF profile.
The data seemed to be there in storage.js.migrated but would need to
convert that to OPML format.
Thanks,
Dave

**Comment by tanriol** [comment] 2023-05-30 09:43
> I was able to get it to work again by exporting OPML from an old profile, and importing the OPML in the new profile.

Glad to hear it's fixed for you, although that sounds like you won't be able to look into the details of the problem.

> Would still be interested to know what happened and how to fix it if I did not have the old FF profile.

Most likely IndexedDB storing the main Brief data broke in some way for some reason. Most likely a Firefox problem caused by something like unclean shutdown. There's not much Brief could do to fix this completely, but error reporting is definitely missing.

> The data seemed to be there in storage.js.migrated but would need to convert that to OPML format.

This is likely an old and incomplete copy from the day Firefox migrated from one storage kind to another. Not sure when that happened off the top of my head.

**Comment by bostongarden** [comment] 2023-05-30 09:44
OK, thanks anyway.
Best regards,
Dave

**Comment by tanriol** [comment] 2023-05-30 09:45
Ok, closing the issue as the problem is gone now for you.

**Closed by tanriol** 2023-05-30 09:45 UTC
