### ISSUE TITLE
Unable to add feed

### ISSUE THREAD

**Issue by sullygirl** [brief-rss/brief#465] opened 2019-07-10 12:32 UTC
I've added a feed that is not showing up in brief.  Please help!

**Comment by tanriol** [comment] 2019-07-10 13:39
Could you provide a few more details:
- how did you add it,
- do other feeds work for you (including marking as read and/or updating),
- what's the problematic feed, if you can share that.

**Comment by sullygirl** [comment] 2019-07-10 13:50
I tried clicking on the RSS link to no avail.  I'm looking to follow certain Supreme Court cases, such as:
https://www.supremecourt.gov/search.aspx?filename=/docket/docketfiles/html/public/18-1269.html
Thanks for any help.

**Comment by tanriol** [comment] 2019-07-10 14:02
This is a duplicate of #462, already a known problem.

For now you can open the developer tools on the Brief tab with F12, open console and subscribe with a command like the following:
```
Database.addFeeds({url: "https://www.supremecourt.gov/rss/cases/18-1269.xml"})
```
where the address was copied by right-clicking the feed icon and choosing "Copy Link Location".

**Comment by tanriol** [comment] 2019-07-10 14:02
Duplicate of #462.

**Closed by tanriol** 2019-07-10 14:02 UTC

**Comment by sullygirl** [comment] 2019-07-10 14:22
Forgive my inexperience - F12 doesn't open anything for me and I see no option in the Brief tab to add feeds. Is there a user manual somewhere?

**Comment by tanriol** [comment] 2019-07-10 14:27
This function is not documented, it's an internal one. Going from the Firefox menus, this is called Web Console and can be found in "Web Developer" or "Tools" - "Web Developer".
