### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by laitcg** [brief-rss/brief#488] opened 2020-02-26 10:34 UTC
Is brief going to be ported to Firefox on Android?

**Comment by tanriol** [comment] 2020-02-26 10:40
I don't have enough time to design a UI that would work for small screens, and the Brief's default UI will not really work. Would be possible if that changed or if someone worked on that.

Oh, and note that the legacy Firefox for Android is going away, being replaced by the new one (Fenix) over 2020, and Fenix so far has very limited extension support.

Closing this issue as a duplicate of #75 - you may want to track that instead.

**Closed by tanriol** 2020-02-26 10:40 UTC
